
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Copied from ExtraCredit, get perm before dist !!

# New context to modify mult/chips before hands are played - used for [Stellar Nursery]
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
match_indent = true
pattern = '''if modded then update_hand_text({sound = 'chips2', modded = modded}, {chips = hand_chips, mult = mult}) end'''
position = "after"
payload = '''
for i=1, #G.jokers.cards do
    eval_card(G.jokers.cards[i], {cardarea = G.jokers, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, before_but_not_as_much = true})
end
'''